#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqPages
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_EMS")]
	public partial class LinqClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Inserttb_stock(tb_stock instance);
    partial void Updatetb_stock(tb_stock instance);
    partial void Deletetb_stock(tb_stock instance);
    #endregion
		
		public LinqClassDataContext() : 
				base(global::LinqPages.Properties.Settings.Default.db_EMSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tb_stock> tb_stock
		{
			get
			{
				return this.GetTable<tb_stock>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_stock")]
	public partial class tb_stock : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _tradecode;
		
		private string _fullname;
		
		private string _type;
		
		private string _standard;
		
		private string _unit;
		
		private string _produce;
		
		private System.Nullable<double> _qty;
		
		private System.Nullable<double> _price;
		
		private System.Nullable<double> _averageprice;
		
		private System.Nullable<double> _saleprice;
		
		private System.Nullable<double> _stockcheck;
		
		private System.Nullable<int> _upperlimit;
		
		private System.Nullable<int> _lowerlimit;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntradecodeChanging(string value);
    partial void OntradecodeChanged();
    partial void OnfullnameChanging(string value);
    partial void OnfullnameChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnstandardChanging(string value);
    partial void OnstandardChanged();
    partial void OnunitChanging(string value);
    partial void OnunitChanged();
    partial void OnproduceChanging(string value);
    partial void OnproduceChanged();
    partial void OnqtyChanging(System.Nullable<double> value);
    partial void OnqtyChanged();
    partial void OnpriceChanging(System.Nullable<double> value);
    partial void OnpriceChanged();
    partial void OnaveragepriceChanging(System.Nullable<double> value);
    partial void OnaveragepriceChanged();
    partial void OnsalepriceChanging(System.Nullable<double> value);
    partial void OnsalepriceChanged();
    partial void OnstockcheckChanging(System.Nullable<double> value);
    partial void OnstockcheckChanged();
    partial void OnupperlimitChanging(System.Nullable<int> value);
    partial void OnupperlimitChanged();
    partial void OnlowerlimitChanging(System.Nullable<int> value);
    partial void OnlowerlimitChanged();
    #endregion
		
		public tb_stock()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tradecode", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string tradecode
		{
			get
			{
				return this._tradecode;
			}
			set
			{
				if ((this._tradecode != value))
				{
					this.OntradecodeChanging(value);
					this.SendPropertyChanging();
					this._tradecode = value;
					this.SendPropertyChanged("tradecode");
					this.OntradecodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this.OnfullnameChanging(value);
					this.SendPropertyChanging();
					this._fullname = value;
					this.SendPropertyChanged("fullname");
					this.OnfullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_standard", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string standard
		{
			get
			{
				return this._standard;
			}
			set
			{
				if ((this._standard != value))
				{
					this.OnstandardChanging(value);
					this.SendPropertyChanging();
					this._standard = value;
					this.SendPropertyChanged("standard");
					this.OnstandardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unit", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string unit
		{
			get
			{
				return this._unit;
			}
			set
			{
				if ((this._unit != value))
				{
					this.OnunitChanging(value);
					this.SendPropertyChanging();
					this._unit = value;
					this.SendPropertyChanged("unit");
					this.OnunitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_produce", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string produce
		{
			get
			{
				return this._produce;
			}
			set
			{
				if ((this._produce != value))
				{
					this.OnproduceChanging(value);
					this.SendPropertyChanging();
					this._produce = value;
					this.SendPropertyChanged("produce");
					this.OnproduceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qty", DbType="Float")]
		public System.Nullable<double> qty
		{
			get
			{
				return this._qty;
			}
			set
			{
				if ((this._qty != value))
				{
					this.OnqtyChanging(value);
					this.SendPropertyChanging();
					this._qty = value;
					this.SendPropertyChanged("qty");
					this.OnqtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float")]
		public System.Nullable<double> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_averageprice", DbType="Float")]
		public System.Nullable<double> averageprice
		{
			get
			{
				return this._averageprice;
			}
			set
			{
				if ((this._averageprice != value))
				{
					this.OnaveragepriceChanging(value);
					this.SendPropertyChanging();
					this._averageprice = value;
					this.SendPropertyChanged("averageprice");
					this.OnaveragepriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saleprice", DbType="Float")]
		public System.Nullable<double> saleprice
		{
			get
			{
				return this._saleprice;
			}
			set
			{
				if ((this._saleprice != value))
				{
					this.OnsalepriceChanging(value);
					this.SendPropertyChanging();
					this._saleprice = value;
					this.SendPropertyChanged("saleprice");
					this.OnsalepriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stockcheck", DbType="Float")]
		public System.Nullable<double> stockcheck
		{
			get
			{
				return this._stockcheck;
			}
			set
			{
				if ((this._stockcheck != value))
				{
					this.OnstockcheckChanging(value);
					this.SendPropertyChanging();
					this._stockcheck = value;
					this.SendPropertyChanged("stockcheck");
					this.OnstockcheckChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_upperlimit", DbType="Int")]
		public System.Nullable<int> upperlimit
		{
			get
			{
				return this._upperlimit;
			}
			set
			{
				if ((this._upperlimit != value))
				{
					this.OnupperlimitChanging(value);
					this.SendPropertyChanging();
					this._upperlimit = value;
					this.SendPropertyChanged("upperlimit");
					this.OnupperlimitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lowerlimit", DbType="Int")]
		public System.Nullable<int> lowerlimit
		{
			get
			{
				return this._lowerlimit;
			}
			set
			{
				if ((this._lowerlimit != value))
				{
					this.OnlowerlimitChanging(value);
					this.SendPropertyChanging();
					this._lowerlimit = value;
					this.SendPropertyChanged("lowerlimit");
					this.OnlowerlimitChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
